[project]
name = "maximal-marginal-relevance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "flake8>=7.2.0",
    "isort>=6.0.1",
    "torch>=2.6.0",
    "transformers>=4.50.3",
]
